### ISSUE TITLE
cairo vm runner failed when compiling cairo without -g option

### ISSUE THREAD

**Issue by XuyangSong** [anoma/aarm-cairo#37]
customer:
performer:
deadline: null
estimated: null
started: null
actual: null
completed: null
confirmed: null
dependencies:
- [ ]

---

<put issue details here>

On branch [xuyang/compiler_without_g_option](https://github.com/anoma/aarm-cairo/tree/xuyang/compiler_without_g_option), the normally compiled juvix/trivial_resource_logic.json would fail by running `mix test test/cairo_logic_test.exs`

Recompiling it with `-g` option would solve it as we discussed @lukaszcz

**Comment by lukaszcz** [comment]
Fixed by https://github.com/anoma/juvix/pull/3238
